/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tik_tok_tac;

import javax.swing.JOptionPane;

/**
 *
 * @author GOLU
 */
public class Tic_Tac_Toe extends javax.swing.JFrame {

    /**
     * Creates new form Tic_Tac_Toe
     *
     */
    public Tic_Tac_Toe() {
        initComponents();
    }
    int turn = 2;
    int btnused[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int pXwon[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int pOwon[] = {0, 0, 0, 0, 0, 0, 0, 0, 0};

    int pXwon() {
        if (pXwon[0] == 1 && pXwon[1] == 1 && pXwon[2] == 1) {
            return 1;
        }
        if (pXwon[3] == 1 && pXwon[4] == 1 && pXwon[5] == 1) {
            return 1;
        }
        if (pXwon[6] == 1 && pXwon[7] == 1 && pXwon[8] == 1) {
            return 1;
        }
        if (pXwon[0] == 1 && pXwon[3] == 1 && pXwon[6] == 1) {
            return 1;
        }
        if (pXwon[1] == 1 && pXwon[4] == 1 && pXwon[7] == 1) {
            return 1;
        }
        if (pXwon[2] == 1 && pXwon[5] == 1 && pXwon[8] == 1) {
            return 1;
        }
        if (pXwon[0] == 1 && pXwon[4] == 1 && pXwon[8] == 1) {
            return 1;
        }
        if (pXwon[2] == 1 && pXwon[4] == 1 && pXwon[6] == 1) {
            return 1;
        }
        return 0;
    }

    int pOwon() {
        if (pOwon[0] == 1 && pOwon[1] == 1 && pOwon[2] == 1) {
            return 1;
        }
        if (pOwon[3] == 1 && pOwon[4] == 1 && pOwon[5] == 1) {
            return 1;
        }
        if (pOwon[6] == 1 && pOwon[7] == 1 && pOwon[8] == 1) {
            return 1;
        }
        if (pOwon[0] == 1 && pOwon[3] == 1 && pOwon[6] == 1) {
            return 1;
        }
        if (pOwon[1] == 1 && pOwon[4] == 1 && pOwon[7] == 1) {
            return 1;
        }
        if (pOwon[2] == 1 && pOwon[5] == 1 && pOwon[8] == 1) {
            return 1;
        }
        if (pOwon[0] == 1 && pOwon[4] == 1 && pOwon[8] == 1) {
            return 1;
        }
        if (pOwon[2] == 1 && pOwon[4] == 1 && pOwon[6] == 1) {
            return 1;
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton4.setText("jButton1");

        jButton5.setText("jButton1");

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tic_Tac_Toe/Golu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 24))); // NOI18N

        b0.setBackground(java.awt.Color.white);
        b0.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b1.setBackground(java.awt.Color.white);
        b1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(java.awt.Color.white);
        b2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b5.setBackground(java.awt.Color.white);
        b5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setBackground(java.awt.Color.white);
        b4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b3.setBackground(java.awt.Color.white);
        b3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b8.setBackground(java.awt.Color.white);
        b8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setBackground(java.awt.Color.white);
        b7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b6.setBackground(java.awt.Color.white);
        b6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.gray);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(java.awt.Color.darkGray);
        jButton1.setText("Play Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.pink);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if (btnused[0] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b0.setText("X");
                btnused[0] = 1;
                pXwon[0] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b0.setText("O");
                btnused[0] = 1;
                pOwon[0] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        b0.setText("");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b8.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");

        turn = 2;

        for (int i = 0; i < 9; i++) {
            btnused[i] = 0;
        }

        for (int i = 0; i < 9; i++) {
            pXwon[i] = 0;
        }
        for (int i = 0; i < 9; i++) {
            pOwon[i] = 0;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if (btnused[1] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b1.setText("X");
                btnused[1] = 1;
                pXwon[1] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b1.setText("O");
                btnused[1] = 1;
                pOwon[1] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (btnused[2] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b2.setText("X");
                btnused[2] = 1;
                pXwon[2] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b2.setText("O");
                btnused[2] = 1;
                pOwon[2] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (btnused[3] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b3.setText("X");
                btnused[3] = 1;
                pXwon[3] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b3.setText("O");
                btnused[3] = 1;
                pOwon[3] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if (btnused[4] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b4.setText("X");
                btnused[4] = 1;
                pXwon[4] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b4.setText("O");
                btnused[4] = 1;
                pOwon[4] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if (btnused[5] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b5.setText("X");
                btnused[5] = 1;
                pXwon[5] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b5.setText("O");
                btnused[5] = 1;
                pOwon[5] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if (btnused[6] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b6.setText("X");
                btnused[6] = 1;
                pXwon[6] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b6.setText("O");
                btnused[6] = 1;
                pOwon[6] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (btnused[7] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b7.setText("X");
                btnused[7] = 1;
                pXwon[7] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b7.setText("O");
                btnused[7] = 1;
                pOwon[7] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (btnused[8] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b8.setText("X");
                btnused[8] = 1;
                pXwon[8] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }
            } else {
                turn++;
                b8.setText("O");
                btnused[8] = 1;
                pOwon[8] = 1;

                int result1 = pXwon();
                int result2 = pOwon();
                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player X won this match :");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, " Player O won this match :");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is alredy used ");
        }
    }//GEN-LAST:event_b8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tic_Tac_Toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tic_Tac_Toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tic_Tac_Toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tic_Tac_Toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tic_Tac_Toe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
